import {test,expect} from '@playwright/test';
test('administrator deep link confirms revocation, retries and signs out current session',async({page})=>{
 let attempts=0;await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{data:{user:{username:'admin',roles:['administrator']},csrfToken:'browser-csrf',demo:false}}}));
 await page.route('**/api/v1/admin/sessions?*',r=>r.fulfill({json:{data:[{handle:'a'.repeat(64),userId:'admin',provider:'local',roles:['administrator'],expires:'2026-10-04T12:00:00Z',current:true}],meta:{limit:25,offset:0,hasMore:false}}}));
 await page.route('**/api/v1/admin/sessions/*/revoke',r=>{attempts++;expect(r.request().headers()['x-csrf-token']).toBe('browser-csrf');expect(r.request().postDataJSON()).toEqual({confirm:true});return r.fulfill(attempts===1?{status:503,json:{error:{message:'Session store unavailable'}}}:{json:{data:{ok:true,current:true}}})});
 await page.goto('/clusters/demo/sessions');await expect(page.getByRole('heading',{name:'Sessions',exact:true})).toBeVisible();const revoke=page.getByRole('button',{name:'Revoke session for admin'});await revoke.scrollIntoViewIfNeeded();await revoke.click();expect(attempts).toBe(0);await expect(page.getByRole('dialog')).toContainText('You will be signed out');await page.getByRole('button',{name:'Confirm revocation'}).click();await expect(page.getByRole('alert')).toContainText('Session store unavailable');await page.getByRole('button',{name:'Confirm revocation'}).click();await expect(page).toHaveURL(/\/login(?:\?|$)/);await expect(page.getByRole('heading',{name:'Welcome to your control plane.'})).toBeVisible();
});
test('non-admin deep link is denied and administration navigation is hidden',async({page})=>{await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{data:{user:{username:'viewer',roles:['viewer']},csrfToken:'csrf',demo:false}}}));await page.goto('/clusters/demo/sessions');await expect(page.getByRole('alert')).toContainText('Administrator access required');await expect(page.getByRole('button',{name:'Sessions',exact:true})).toHaveCount(0)});
test('mobile sessions table remains bounded and demo offers no revocation',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{data:{user:{username:'admin',roles:['administrator']},csrfToken:'csrf',demo:false}}}));await page.route('**/api/v1/admin/sessions?*',r=>r.fulfill({json:{data:[{handle:'b'.repeat(64),userId:'alice',provider:'oidc',roles:['viewer'],expires:'2026-10-04T12:00:00Z',current:false}],meta:{limit:25,offset:0,hasMore:false}}}));await page.goto('/clusters/demo/sessions');await expect(page.getByText('alice',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{data:{user:{username:'demo',roles:['administrator']},csrfToken:'csrf',demo:true}}}));await page.reload();await expect(page.getByText(/Session revocation is unavailable/)).toBeVisible();await expect(page.getByRole('button',{name:/Revoke session/})).toHaveCount(0);
});

test('configured session manager capability exposes administration navigation',async({page})=>{await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{data:{user:{username:'security',roles:['session-manager']},csrfToken:'csrf',demo:false,canManageSessions:true}}}));await page.route('**/api/v1/admin/sessions?*',r=>r.fulfill({json:{data:[],meta:{limit:25,offset:0,hasMore:false}}}));await page.goto('/clusters/demo/overview');const nav=page.getByRole('button',{name:'Sessions',exact:true});await nav.scrollIntoViewIfNeeded();await nav.click();await expect(page.getByText('No active sessions.')).toBeVisible()});
