import {test,expect,type Page} from '@playwright/test';
async function pickTopic(page:Page,name:string){const input=page.getByRole('combobox',{name:'Topic',exact:true});await input.fill(name);await page.getByRole('option',{name,exact:true}).click()}
test('Protobuf value selection sends the correct decoder and retains original bytes',async({page})=>{
 await page.route('**/api/v1/clusters/demo/schemas',route=>route.fulfill({json:{data:[{id:'sr'}]}}));
 await page.route('**/api/v1/clusters/demo/messages?*',route=>{
  const params=new URL(route.request().url()).searchParams;
  const protobuf=params.get('decoder')==='protobuf';
  if(protobuf)expect(params.get('registry')).toBe('sr');
  return route.fulfill({json:{data:[{partition:0,offset:42,timestamp:new Date().toISOString(),key:'event',keyBase64:'AAAAACoACgNhYmM=',value:'binary',valueBase64:'AAAAACoACgNhYmM=',headers:[],...(protobuf?{decodedValue:{name:'abc'},schemaId:42,decodedFormat:'protobuf'}:{}),...(protobuf&&params.get('decoderTarget')==='both'?{decodedKey:{name:'abc'},keySchemaId:42,keyDecodedFormat:'protobuf'}:{})}]}});
 });
 await page.goto('/clusters/demo/messages');
 await pickTopic(page,'orders.created');
 await page.locator('.record-summary').first().click();
 await page.getByLabel('Value decoder').selectOption({label:'Protobuf · sr'});
 const value=page.locator('.record-detail > .payload');
 await value.getByRole('button',{name:'Schema',exact:true}).click();
 await expect(value.getByText('Protobuf · schema 42')).toBeVisible();
 await expect(value.getByText('"abc"')).toBeVisible();
 await value.getByRole('button',{name:'Base64',exact:true}).click();
 await expect(value.getByText('AAAAACoACgNhYmM=')).toBeVisible();
 await page.getByLabel('Decode field',{exact:true}).selectOption('both');
 await page.getByRole('tab',{name:'Key',exact:true}).click();
 const key=page.locator('.record-detail > .payload');
 await key.getByRole('button',{name:'Schema',exact:true}).click();
 await expect(key.getByText('Protobuf · schema 42')).toBeVisible();
 await expect(key.getByText('"abc"')).toBeVisible();
 await key.getByRole('button',{name:'Base64',exact:true}).click();
 await expect(key.getByText('AAAAACoACgNhYmM=')).toBeVisible();
});
test('Avro value decoding retains raw bytes and explains individual failures',async({page})=>{
 await page.route('**/api/v1/clusters/demo/schemas',route=>route.fulfill({json:{data:[{id:'sr'}]}}));
 await page.route('**/api/v1/clusters/demo/messages?*',route=>{
  const decoded=new URL(route.request().url()).searchParams.get('decoder')==='avro';
  return route.fulfill({json:{data:[{partition:0,offset:42,timestamp:new Date().toISOString(),key:'event',value:'binary preview',valueBase64:'AAAAACoGYWJj',headers:[],...(decoded?{decodedValue:{name:'abc'},schemaId:42}:{})}]}});
 });
 await page.goto('/clusters/demo/messages');
 await pickTopic(page,'orders.created');
 await page.locator('.record-summary').first().click();
 await page.getByLabel('Value decoder').selectOption('sr');
 const value=page.locator('.record-detail > .payload');
 await value.getByRole('button',{name:'Schema',exact:true}).click();
 await expect(value.getByText('Avro · schema 42')).toBeVisible();
 await expect(value.getByText('"abc"')).toBeVisible();
 await value.getByRole('button',{name:'Base64',exact:true}).click();
 await expect(value.getByText('AAAAACoGYWJj')).toBeVisible();
 await page.route('**/api/v1/clusters/demo/messages?*',route=>route.fulfill({json:{data:[{partition:0,offset:42,timestamp:new Date().toISOString(),key:'event',value:'binary preview',valueBase64:'AAAAACoGYWJj',headers:[],schemaId:42,decodeError:'Schema registry unavailable or schema subject permission denied'}]}}));
 await page.getByRole('button',{name:'Fetch',exact:true}).click();
 await value.getByRole('button',{name:'Schema',exact:true}).click();
 await expect(value.getByRole('status')).toContainText('Schema registry unavailable');
 await page.setViewportSize({width:390,height:844});
 await expect.poll(()=>page.locator('.sidebar').evaluate(node=>node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'artifacts/avro-inspection-mobile.png',fullPage:true,animations:'disabled'});
});
test('live throttle review distinguishes a pending request from the verified rate',async({page})=>{
  const id='a'.repeat(64);
  const plan={id,state:'running',topics:['orders.created'],planHash:'exact-rate-hash',createdAt:new Date().toISOString(),before:[],after:[],changes:[],throttleBytesPerSec:100};
  let current:typeof plan&{throttleRequest?:{revision:string;bytesPerSec:number}}=plan;
  await page.route('**/api/v1/clusters/demo/rebalances',route=>route.fulfill({json:{data:[current]}}));
  await page.route(`**/api/v1/clusters/demo/rebalances/${id}`,route=>route.fulfill({json:{data:current}}));
  await page.route(`**/api/v1/clusters/demo/rebalances/${id}/throttle`,async route=>{
    expect(route.request().postDataJSON()).toEqual({confirmation:true,planHash:'exact-rate-hash',bytesPerSec:200});
    current={...plan,throttleRequest:{revision:'requested',bytesPerSec:200}};
    await route.fulfill({json:{data:current}});
  });
  await page.goto('/clusters/demo/reassignments');
  await page.getByRole('button',{name:new RegExp(`${id}.*orders.created`)}).click();
  await page.getByRole('button',{name:'Change throttle',exact:true}).click();
  await page.getByLabel('New rate · bytes per second').fill('200');
  await expect(page.getByRole('button',{name:'Request throttle change'})).toBeDisabled();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.screenshot({path:'artifacts/throttle-review-mobile.png',fullPage:true,animations:'disabled'});
  await page.getByLabel('Confirm job ID').fill(id);
  await page.getByRole('button',{name:'Request throttle change'}).click();
  await expect(page.getByText('Requested: 200 B/s — awaiting worker verification')).toBeVisible();
  await expect(page.getByText('Current job throttle: 100 B/s')).toBeVisible();
  current={...plan,throttleBytesPerSec:200};
  await expect(page.getByText('Current job throttle: 200 B/s')).toBeVisible({timeout:10000});
  await expect(page.getByText('Requested: 200 B/s — awaiting worker verification')).toHaveCount(0);
});
test('configured integration workspaces explain missing services',async({page})=>{
  await page.goto('/clusters/demo/schemas');
  await expect(page.getByText(/No Schema Registry integration is configured/)).toBeVisible();
  await expect(page.getByRole('button',{name:'Register schema',exact:true})).toHaveCount(0);
  await page.goto('/clusters/demo/connect');
  await expect(page.getByText(/No Kafka Connect integration is configured/)).toBeVisible();
  await page.screenshot({path:'artifacts/connect-unconfigured.png',fullPage:true,animations:'disabled'});
});
test('configured cluster wizard returns real sanitized diagnostics',async({page})=>{
  await page.goto('/clusters/demo/settings');
  await page.getByRole('button',{name:'Review diagnostic'}).click();
  await page.getByRole('button',{name:'Test connection',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Connection diagnostic result'})).toBeVisible();
  await page.screenshot({path:'artifacts/cluster-diagnostic.png',fullPage:true,animations:'disabled'});
});
test('Kafka ACL bindings create, filter, raw inspect and exact delete',async({page})=>{
  const name=`User:kaflux-e2e-${Date.now()}`;
  await page.goto('/clusters/demo/acls');
  await page.getByRole('button',{name:'Create ACL',exact:true}).click();
  await page.getByLabel('Resource name',{exact:true}).fill('orders.created');
  await page.getByLabel('Principal',{exact:true}).fill(name);
  await expect(page.getByRole('button',{name:'Confirm creation'})).toBeDisabled();
  await page.getByLabel('I reviewed this exact ACL binding.').check();
  await page.getByRole('button',{name:'Confirm creation'}).click();
  await expect(page.getByRole('status')).toHaveText('ACL binding created.');
  await page.getByLabel('Filter ACL principal').fill(name);
  await expect(page.getByRole('cell',{name,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Raw Kafka',exact:true}).click();
  await expect(page.locator('.acl-raw')).toContainText('"raw"');
  await page.getByRole('button',{name:'Readable',exact:true}).click();
  await page.screenshot({path:'artifacts/access-control.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Delete ACL',exact:true}).click();
  await expect(page.getByRole('button',{name:'Confirm deletion'})).toBeDisabled();
  await page.getByLabel('I reviewed this exact ACL binding.').check();
  await page.getByRole('button',{name:'Confirm deletion'}).click();
  await expect(page.getByRole('status')).toHaveText('ACL binding deleted.');
});
test('live tail advances beyond a bounded initial read and discovers produced records',async({page})=>{
  const key=`tail-regression-${Date.now()}`;
  await page.goto('/clusters/demo/messages');
  const session=await (await page.request.get('/api/v1/auth/session')).json();
  for(let i=0;i<5;i++){
    const response=await page.request.post('/api/v1/clusters/demo/messages',{headers:{'X-CSRF-Token':session.data.csrfToken},data:{topic:'orders.created',partition:0,key:`bounded-seed-${Date.now()}-${i}`,value:'bounded tail test fixture',headers:[]}});
    expect(response.ok()).toBeTruthy();
  }
  await pickTopic(page,'orders.created');
  await page.getByLabel('Record limit').selectOption('25');
  await expect(page.locator('.record')).toHaveCount(25);
  await page.getByRole('button',{name:'Start live tail'}).click();
  await page.getByRole('button',{name:'Produce',exact:true}).click();
  await page.getByLabel('Message key').fill(key);
  await page.getByLabel('Message value').fill('{"type":"tail-verification"}');
  await page.getByRole('button',{name:'Confirm & produce'}).click();
  await expect(page.locator('.record').filter({hasText:key})).toBeVisible({timeout:15000});
  await page.getByLabel('Search returned records').fill(key);
  await expect(page.locator('.record')).toHaveCount(1);
  await page.getByRole('button',{name:'Pause live tail'}).click();
});
test('cancelling a running reassignment requires approval and sends the reviewed hash',async({page})=>{
  const plan={id:'cancel-review',state:'running',topics:['orders.created'],planHash:'exact-cancel-hash',createdAt:new Date().toISOString(),before:[],after:[],changes:[]};
  await page.route('**/api/v1/clusters/demo/rebalances',route=>route.fulfill({json:{data:[plan]}}));
  await page.route('**/api/v1/clusters/demo/rebalances/cancel-review',route=>route.fulfill({json:{data:plan}}));
  await page.route('**/api/v1/clusters/demo/rebalances/cancel-review/cancel',async route=>{expect(route.request().postDataJSON()).toEqual({confirmation:true,planHash:'exact-cancel-hash'});await route.fulfill({json:{data:{...plan,state:'cancelled'}}})});
  await page.goto('/clusters/demo/reassignments');
  await page.getByRole('button',{name:/cancel-review.*orders.created/}).click();
  await expect(page.getByRole('button',{name:'Cancel reassignment',exact:true})).toBeDisabled();
  await page.getByLabel('I reviewed the replica changes and approve this exact plan.').check();
  await page.getByRole('button',{name:'Cancel reassignment',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Cancellation requested');
});
test('topic administration creates, configures, expands and deletes a reviewed topic',async({page})=>{
  const name=`kaflux-workflow-${Date.now()}`;
  await page.goto('/clusters/demo/topics');
  await page.getByRole('button',{name:'Create topic',exact:true}).click();
  await page.getByLabel('Topic name',{exact:true}).fill(name);
  await page.getByRole('button',{name:'Confirm creation'}).click();
  await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Edit configuration'}).click();
  await page.getByLabel(/^retention\.ms/).fill('86400000');
  await page.getByLabel(/^compression\.type/).selectOption('zstd');
  await expect(page.getByLabel('Pending changes')).toContainText('2 pending changes');
  await page.getByRole('button',{name:'Apply 2 changes'}).click();
  await expect(page.getByRole('status')).toContainText('completed');
  await page.getByRole('button',{name:'Configuration',exact:true}).click();
  await expect(page.locator('.config-row.override').filter({hasText:'compression.type'})).toContainText('zstd');
  await page.getByRole('button',{name:'Add partitions'}).click();
  await page.getByLabel('New total partition count').fill('4');
  await page.getByRole('button',{name:'Confirm change'}).click();
  await expect(page.getByRole('status')).toContainText('completed');
  await page.screenshot({path:'artifacts/topic-administration.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Delete topic',exact:true}).click();
  await expect(page.getByRole('button',{name:'Confirm deletion'})).toBeDisabled();
  await page.getByLabel('Type the topic name to confirm').fill(name);
  await page.getByRole('button',{name:'Confirm deletion'}).click();
  await expect(page.getByRole('heading',{name:'Topics',exact:true})).toBeVisible();
  await expect(page.locator('.topic-name').filter({hasText:name})).toHaveCount(0);
});
test('inactive group offset reset requires preview and typed approval',async({page})=>{
  await page.goto('/clusters/demo/consumer-groups');
  await page.getByRole('button',{name:'demo-inactive',exact:true}).click();
  await expect(page.getByRole('columnheader',{name:'Committed offset',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Reset offsets',exact:true}).click();
  await page.getByLabel('Reset strategy').selectOption('earliest');
  await page.getByRole('button',{name:'Preview offset changes'}).click();
  await expect(page.getByRole('heading',{name:'Reviewed partition changes'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Confirm offset reset'})).toBeDisabled();
  await page.getByLabel('Type the group ID to confirm').fill('demo-inactive');
  await page.screenshot({path:'artifacts/consumer-reset-review.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Confirm offset reset'}).click();
  await expect(page.getByRole('status')).toHaveText('Consumer offsets reset.');
});
test('demo inventory, record inspection, live tail, theme and deep links',async({page})=>{
  await page.goto('/clusters/demo/overview');
  await expect(page.getByText('DEMO SIMULATOR')).toBeVisible();
  await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();
  await expect(page.getByText('Broker distribution',{exact:true})).toBeVisible();
  await page.screenshot({path:'artifacts/overview-desktop.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Topics',exact:false}).first().click();
  await expect(page.getByRole('textbox',{name:'Search topics'})).toBeVisible();
  await expect(page.locator('.topic-name').first()).toBeVisible();
  const topic=(await page.locator('.topic-name').first().innerText()).trim();
  await page.goto('/clusters/demo/messages');
  await pickTopic(page,topic);
  await expect(page.locator('.record').first()).toBeVisible();
  await page.locator('.record-summary').first().click();
  await expect(page.locator('.record-detail .payload').first()).toBeVisible();
  await page.getByRole('button',{name:'Hex',exact:true}).first().click();
  await expect(page.locator('.payload-code pre').first()).toContainText(/[0-9a-f]{2}/);
  await page.getByRole('button',{name:'JSON',exact:true}).first().click();
  await page.getByRole('button',{name:'Start live tail'}).click();
  await expect(page.getByRole('button',{name:'Pause live tail'})).toBeVisible();
  await page.getByRole('button',{name:'Pause live tail'}).click();
  await page.screenshot({path:'artifacts/messages-desktop.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Toggle light theme'}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/messages-mobile.png',fullPage:true,animations:'disabled'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.goto('/clusters/demo/overview');
  await expect(page.getByRole('button',{name:'Toggle navigation'})).toBeVisible();
  await page.screenshot({path:'artifacts/overview-mobile.png',fullPage:true,animations:'disabled'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
test('mutation authorization and exact plan approval',async({page})=>{
  await page.goto('/clusters/demo/reassignments');
  await page.getByLabel('Topics',{exact:true}).fill('orders.created');
  await page.getByRole('option',{name:'orders.created',exact:true}).click();
  await expect(page.getByRole('button',{name:'Remove orders.created'})).toBeVisible();
  await page.getByRole('button',{name:'Generate plan',exact:true}).click();
  await expect(page.getByText(/Review plan ·/)).toBeVisible();
  await page.getByRole('button',{name:'Validate dry run',exact:true}).click();
  await expect(page.getByText('Dry run valid',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Execute plan'})).toBeDisabled();
  await page.getByLabel('I reviewed the replica changes and approve this exact plan.').check();
  await expect(page.getByRole('button',{name:'Execute plan'})).toBeEnabled();
});
test('MSK active intelligent balancing blocks manual plans with actionable reason',async({page})=>{
  await page.route('**/api/v1/clusters/demo/capabilities',route=>route.fulfill({json:{data:{manualReassignmentAllowed:false,rebalancingStatus:'ACTIVE',reason:'MSK intelligent rebalancing is active.',kind:'msk',brokerType:'express',observedAt:new Date().toISOString()}}}));
  await page.goto('/clusters/demo/reassignments');
  await expect(page.getByText('AWS owns partition balancing')).toBeVisible();
  await expect(page.getByRole('button',{name:'Generate plan',exact:true})).toBeDisabled();
  await page.goto('/clusters/demo/brokers/balance');
  await expect(page.getByText('AWS owns partition balancing')).toBeVisible();
  await expect(page.getByRole('button',{name:'Generate plan',exact:true})).toBeDisabled();
  await expect(page.getByRole('heading',{name:'Distribution analysis'})).toBeVisible();
});
test('old balance links open the Balance tab under Brokers',async({page})=>{
  await page.goto('/clusters/demo/balance');
  await expect(page).toHaveURL(/\/clusters\/demo\/brokers\/balance(\?|$)/);
  await expect(page.getByRole('heading',{name:'Distribution analysis'})).toBeVisible();
  await page.getByRole('button',{name:'Brokers',exact:true}).last().click();
  await expect(page).toHaveURL(/\/clusters\/demo\/brokers(\?|$)/);
});
test('topic distribution hands its topic to the reassignment planner',async({page})=>{
  await page.goto('/clusters/demo/topics');
  await page.getByText('orders.created',{exact:true}).first().click();
  await page.getByRole('button',{name:'Distribution',exact:true}).click();
  await page.getByRole('button',{name:'Plan reassignment'}).click();
  await expect(page).toHaveURL(/reassignments/);
  await expect(page.getByRole('button',{name:'Remove orders.created'})).toBeVisible();
});
test('operation history deletes a planned reassignment',async({page})=>{
  await page.goto('/clusters/demo/reassignments');
  await page.getByLabel('Topics',{exact:true}).fill('orders.created');
  await page.getByRole('option',{name:'orders.created',exact:true}).click();
  await page.getByRole('button',{name:'Generate plan',exact:true}).click();
  await expect(page.getByText(/Review plan ·/)).toBeVisible();
  const n=await page.getByRole('button',{name:/^Delete plan /}).count();
  await page.getByRole('button',{name:/^Delete plan /}).first().click();
  await page.getByRole('button',{name:'Confirm deletion'}).click();
  await expect(page.getByText('Plan deleted.')).toBeVisible();
  await expect(page.getByRole('button',{name:/^Delete plan /})).toHaveCount(n-1);
});
test('overview throughput charts bytes in and bytes out as two series',async({page})=>{
 await page.goto('/');
 const panel=page.locator('.traffic-panel');
 await panel.scrollIntoViewIfNeeded();
 await expect(panel.getByText('Bytes in · Bytes out')).toBeVisible();
 await expect(panel.locator('.u-legend').getByText('Bytes in',{exact:false})).toBeVisible({timeout:20000});
 await expect(panel.locator('.u-legend').getByText('Bytes out',{exact:false})).toBeVisible();
 await panel.getByRole('button',{name:'Table'}).click();
 const table=panel.getByRole('table',{name:'Bytes in · Bytes out by series'});
 await expect(table.getByRole('cell',{name:'Bytes in',exact:true})).toBeVisible();
 await expect(table.getByRole('cell',{name:'Bytes out',exact:true})).toBeVisible();
});
test('overview throughput keeps bytes in when bytes out is unavailable',async({page})=>{
 await page.route('**/api/v1/clusters/demo/metrics/query?metric=egress*',route=>route.fulfill({status:503,json:{error:{message:'datasource down'}}}));
 await page.goto('/');
 const panel=page.locator('.traffic-panel');
 await panel.scrollIntoViewIfNeeded();
 await expect(panel.locator('.u-legend').getByText('Bytes in',{exact:false})).toBeVisible({timeout:20000});
 await expect(panel.getByText('Bytes out unavailable',{exact:false})).toBeVisible();
 await expect(panel.locator('.u-legend').getByText('Bytes out',{exact:false})).toHaveCount(0);
});
