import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowRight,Check,Database,Layers3,Pencil,Plus,Settings,Shield,Trash2,X} from 'lucide-react';
import {api,pretty,type Cluster,type Session} from './api';

function canAdmin(session?:Session){return session?.user.role==='administrator'||session?.user.roles?.includes('administrator')}
function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description:string;children:React.ReactNode}){
  return <Dialog.Root open={open} onOpenChange={value=>{if(!value)onClose()}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog"><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description><Dialog.Close className="dialog-close" aria-label="Close"><X size={18}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>
}
export function TopicAdministration({clusterId,topic,session,onCreated,onDeleted}:{clusterId:string;topic?:string;session?:Session;onCreated?:(name:string)=>void;onDeleted?:()=>void}){
  const [action,setAction]=useState('');const [name,setName]=useState('');const [partitions,setPartitions]=useState('3');const [replication,setReplication]=useState('3');const [retention,setRetention]=useState('604800000');const [cleanup,setCleanup]=useState('delete');const [confirmation,setConfirmation]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const queryClient=useQueryClient();
  async function open(value:string){setAction(value);setConfirmation('');setError('');setNotice('');if(topic&&(value==='config'||value==='partitions')){setBusy(true);try{if(value==='config'){const result=await api<Record<string,string>>(`/clusters/${clusterId}/topics/${encodeURIComponent(topic)}/config`);setRetention(String(result.data['retention.ms']??''));setCleanup(result.data['cleanup.policy']??'delete')}else{const result=await api<{partitions:number|unknown[]}>(`/clusters/${clusterId}/topics/${encodeURIComponent(topic)}`);setPartitions(String((Array.isArray(result.data.partitions)?result.data.partitions.length:result.data.partitions)+1))}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}
  const title=action==='create'?'Create topic':action==='delete'?'Delete topic':action==='partitions'?'Increase partition count':'Update topic configuration';
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{
    const path=`/clusters/${clusterId}/topics${topic?`/${encodeURIComponent(topic)}`:''}`;
    if(action==='create')await api(path,{method:'POST',body:JSON.stringify({name,partitions:Number(partitions),replicationFactor:Number(replication),config:{'retention.ms':retention,'cleanup.policy':cleanup}})});
    else if(action==='delete')await api(path,{method:'DELETE',body:JSON.stringify({confirmation:topic})});
    else if(action==='partitions')await api(path+'/partitions',{method:'POST',body:JSON.stringify({count:Number(partitions),confirmation:true})});
    else await api(path+'/config',{method:'POST',body:JSON.stringify({config:{'retention.ms':retention,'cleanup.policy':cleanup},confirmation:true})});
    await queryClient.invalidateQueries();setAction('');setNotice(`${title} completed.`);if(action==='create')onCreated?.(name);if(action==='delete')onDeleted?.();
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <><div className="topic-administration">{topic?<><button className="button" disabled={!canAdmin(session)} onClick={()=>open('config')}><Settings size={14}/>Edit configuration</button><button className="button" disabled={!canAdmin(session)} onClick={()=>open('partitions')}><Layers3 size={14}/>Add partitions</button><button className="button danger-button" disabled={!canAdmin(session)} onClick={()=>open('delete')}><Trash2 size={14}/>Delete topic</button></>:<button className="button primary" disabled={!canAdmin(session)} onClick={()=>open('create')}><Plus size={14}/>Create topic</button>}</div><Modal open={!!action} onClose={()=>setAction('')} title={title} description="Review the exact change. Backend authorization and audit logging apply to every request."><form onSubmit={submit}>{topic&&<div className="review-destination">Resource<strong>{topic}</strong></div>}{action==='create'&&<label>Topic name<input autoFocus value={name} onChange={e=>setName(e.target.value)} pattern="[a-zA-Z0-9._-]+" maxLength={249} required placeholder="orders.created"/></label>}{(action==='create'||action==='partitions')&&<label>{action==='partitions'?'New total partition count':'Partitions'}<input type="number" min="1" max="10000" value={partitions} onChange={e=>setPartitions(e.target.value)} required/></label>}{action==='create'&&<label>Replication factor<input type="number" min="1" max="100" value={replication} onChange={e=>setReplication(e.target.value)} required/></label>}{(action==='create'||action==='config')&&<><label>Retention · milliseconds<input type="number" min="-1" value={retention} onChange={e=>setRetention(e.target.value)} required/></label><label>Cleanup policy<select value={cleanup} onChange={e=>setCleanup(e.target.value)}><option value="delete">delete</option><option value="compact">compact</option><option value="compact,delete">compact,delete</option></select></label></>}{action==='partitions'&&<div className="mutation-warning"><Shield size={16}/><p>Partition count can only increase. Key-based routing may change when producers discover the new partition count.</p></div>}{action==='delete'&&<><div className="mutation-warning"><Trash2 size={16}/><p>Deletion removes this topic and its records. This action cannot be rolled back through Kaflux.</p></div><label>Type the topic name to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} required autoComplete="off"/></label></>}{error&&<div className="inline-error" role="alert">{error}</div>}<button className={`button ${action==='delete'?'danger-button':'primary'}`} disabled={busy||action==='delete'&&confirmation!==topic}>{busy?'Submitting…':`Confirm ${action==='create'?'creation':action==='delete'?'deletion':'change'}`}<ArrowRight size={14}/></button></form></Modal>{notice&&<div className="toast" role="status" onClick={()=>setNotice('')}>{notice}<X size={14}/></div>}</>
}
function ClusterName({cluster,session}:{cluster:Cluster;session?:Session}){
  const [name,setName]=useState(cluster.name);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const queryClient=useQueryClient();const admin=canAdmin(session);
  async function save(value:string){setBusy(true);setError('');setNotice('');try{const result=await api<{name:string}>(`/clusters/${cluster.id}/name`,{method:'PUT',body:JSON.stringify({name:value})});setName(result.data.name);await queryClient.invalidateQueries({queryKey:['/clusters']});setNotice('Cluster name saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="panel"><div className="panel-title"><div><h2>Display name</h2><p>How this cluster appears in Kaflux for every user. The configured name is <strong>{cluster.configuredName}</strong>.</p></div><Pencil size={18}/></div>{error&&<div className="inline-error" role="alert">{error}</div>}{notice&&<div className="inline-notice" role="status">{notice}</div>}<form onSubmit={e=>{e.preventDefault();save(name)}}><label>Cluster name<input value={name} onChange={e=>setName(e.target.value)} maxLength={64} required disabled={!admin} placeholder={cluster.configuredName}/></label><div className="wizard-actions">{cluster.name!==cluster.configuredName&&<button type="button" className="button" disabled={!admin||busy} onClick={()=>save('')}>Reset to configured name</button>}<button className="button primary" disabled={!admin||busy||!name.trim()||name.trim()===cluster.name}>{busy?'Saving…':'Save name'}</button></div></form></section>
}
export function ClusterSettings({clusterId,cluster,session}:{clusterId:string;cluster?:Cluster;session?:Session}){
  const config=useQuery({queryKey:['configuration',clusterId],queryFn:()=>api<Record<string,unknown>>(`/clusters/${clusterId}/configuration`)});
  const [step,setStep]=useState(0);const [result,setResult]=useState<Record<string,unknown>|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function test(){setBusy(true);setError('');try{setResult((await api<Record<string,unknown>>(`/clusters/${clusterId}/test`,{method:'POST',body:JSON.stringify({confirmation:true})})).data);setStep(2)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <>{cluster&&<ClusterName key={cluster.id+cluster.name} cluster={cluster} session={session}/>}<section className="panel"><div className="panel-title"><div><h2>Configured cluster</h2><p>Sanitized capability and connection metadata. Secrets stay on the server.</p></div><span className="tiny-badge">READ ONLY</span></div>{config.error&&<div className="inline-error" role="alert">{config.error.message}</div>}<div className="detail-grid">{Object.entries(config.data?.data??{}).map(([k,v])=><div key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong>{typeof v==='object'?pretty(v):String(v??'Unknown')}</strong></div>)}</div></section><section className="panel"><div className="panel-title"><div><h2>Connection diagnostic wizard</h2><p>Verify the configured broker connection before investigating operations.</p></div><Database size={18}/></div><div className="wizard"><div className="wizard-steps">{['Review cluster','Verify connection','Inspect results'].map((label,i)=><span className={i===step?'active':i<step?'complete':''} key={label}><b>{i<step?<Check size={11}/>:i+1}</b>{label}</span>)}</div>{step===0?<><h3>Use the server-managed connection</h3><p>Kaflux tests the selected cluster using its configured TLS and authentication settings. Credentials and broker addresses are never copied into this wizard.</p><div className="review-destination">Cluster<strong>{clusterId}</strong></div><button className="button primary" onClick={()=>setStep(1)}>Review diagnostic <ArrowRight size={14}/></button></>:step===1?<><h3>Run a bounded connection check</h3><p>The backend checks connectivity and returns sanitized diagnostics. It does not modify topics, consumer offsets, or broker configuration.</p>{error&&<div className="inline-error" role="alert">{error}</div>}<div className="wizard-actions"><button className="button" onClick={()=>setStep(0)}>Back</button><button className="button primary" disabled={busy} onClick={test}>{busy?'Testing…':'Test connection'}<ArrowRight size={14}/></button></div></>:<><h3>Connection diagnostic result</h3><div className="detail-grid">{Object.entries(result??{}).map(([k,v])=><div key={k}><span>{k}</span><strong>{typeof v==='object'?pretty(v):String(v??'Unknown')}</strong></div>)}</div><button className="button" onClick={()=>setStep(0)}>Run another check</button></>}</div></section></>
}
