export type Cluster = {id:string;name:string;environment:string;kind:string;mode:string;state:string;brokerCount:number;topicCount:number;partitionCount:number};
export type Topic = {name:string;partitions:number;replicationFactor:number;sizeBytes:number|null;urp:number;cleanupPolicy:string;retentionMs:number;observedAt:string};
export type Broker = {id:number;host:string;port:number;rack:string;partitions:number;leaders:number;sizeBytes:number|null};
export type Message = {partition:number;offset:number;timestamp:string;key:unknown;value:unknown;headers:{key:string;value:string}[];valueBase64?:string;keyBase64?:string;truncated?:boolean;decodedValue?:unknown;schemaId?:number;decodeError?:string;decodedFormat?:string;decodedKey?:unknown;keyDecodedFormat?:string;keySchemaId?:number;keyDecodeError?:string};
export type Session = {user:{username:string;name?:string;role?:string;roles?:string[];permissions?:string[]};csrfToken:string;demo:boolean;canManageSessions?:boolean};
export type Envelope<T> = {data:T;meta?:{total:number;page:number;pageSize:number}};
export class ApiError extends Error {code:string;status:number;constructor(message:string,code:string,status:number){super(message);this.code=code;this.status=status}}
let csrf='';
export function setCsrf(value:string){csrf=value}
export async function api<T>(path:string,options:RequestInit={}):Promise<Envelope<T>> {
  const response=await fetch(`/api/v1${path}`,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.method&&options.method!=='GET'?{'X-CSRF-Token':csrf}:{}),...options.headers}});
  const body=await response.json().catch(()=>null);
  if(!response.ok)throw new ApiError(body?.error?.message??`Request failed (${response.status})`,body?.error?.code??'REQUEST_FAILED',response.status);
  return body;
}
export function pretty(value:unknown){if(typeof value==='string'){try{return JSON.stringify(JSON.parse(value),null,2)}catch{return value}}return JSON.stringify(value,null,2)??'null'}
export function asJson(value:unknown):unknown{if(typeof value==='string'){try{return JSON.parse(value)}catch{return value}}return value}
export function hex(value:unknown){return Array.from(new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)??'')).map(x=>x.toString(16).padStart(2,'0')).join(' ')}
export function bytes(value:number|null|undefined){if(value==null)return 'Unavailable';if(value<1024)return `${Number.isInteger(value)?value:value.toFixed(1)} B`;const n=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return `${(value/1024**n).toFixed(1)} ${['B','KiB','MiB','GiB','TiB'][n]}`}
const compact=new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1});
// Units follow the Grafana unit identifiers used by the metric catalog.
export function metricValue(value:number,unit=''){switch(unit){case 'Bps':return `${bytes(value)}/s`;case 'decbytes':return bytes(value);case 'bps':return `${compact.format(value)} b/s`;case 'reqps':return `${compact.format(value)}/s`;case 'percent':return `${compact.format(value)}%`;case 'percentunit':return `${compact.format(value*100)}%`;case 'ms':case 'ns':case 's':return `${compact.format(value)} ${unit}`;default:return compact.format(value)}}
export type MetricResult = {status:string;observedAt:string;series:{name?:string;labels?:Record<string,string>;points?:({time:number;value:number}|number[])[];values?:number[][]}[];error?:string;stale?:boolean};
export function latestSample(result:MetricResult|undefined){if(result?.status!=='available')return undefined;const series=result.series[0];const point=(series?.points??series?.values)?.at(-1);const value=point==null?undefined:Number(Array.isArray(point)?point[1]:point.value);return Number.isFinite(value)?value:undefined}
// Series follow the catalog's Grafana legendFormat ({{label}}); when it is missing or ambiguous, the labels that differ between series name them.
export function seriesNames(series:MetricResult['series'],legend='',fallback=''){const labels=series.map(s=>Object.fromEntries(Object.entries(s.labels??{}).filter(([k])=>k!=='__name__')));const templated=legend.includes('{{')||series.length===1?series.map((_,i)=>legend.replace(/\{\{\s*([\w.]+)\s*\}\}/g,(_,k:string)=>labels[i][k]??'').trim()):[];const varying=[...new Set(labels.flatMap(Object.keys))].filter(k=>new Set(labels.map(l=>l[k])).size>1);const unique=templated.every(Boolean)&&new Set(templated).size===series.length;return series.map((s,i)=>s.name||(unique?templated[i]:varying.map(k=>labels[i][k]).filter(Boolean).join(' · '))||(series.length===1&&fallback)||`Series ${i+1}`)}
export type MetricLine={name:string;values:(number|null)[];latest?:number;average?:number;peak?:number};
export type PreparedMetric={timestamps:number[];all:MetricLine[];shown:MetricLine[];other?:MetricLine;slots:Map<string,number>};
// Rates and sizes add up across brokers or topics, so the long tail folds into one "Other" line; other units are ranked and truncated instead.
const additiveUnits=new Set(['Bps','bps','reqps','decbytes','bytes']);
export function prepareMetric(series:MetricResult['series'],{legend='',label='',unit='',limit=8}={}):PreparedMetric{const names=seriesNames(series,legend,label);const samples=series.map(s=>new Map((s.points??s.values??[]).map(p=>Array.isArray(p)?[p[0],p[1]]:[p.time,p.value])));const timestamps=[...new Set(samples.flatMap(m=>[...m.keys()]))].sort((a,b)=>a-b);const all=samples.map((m,i)=>{const values=timestamps.map(t=>{const v=m.get(t);return v!=null&&Number.isFinite(v)?v:null});const present=values.filter((v):v is number=>v!=null);return {name:names[i],values,latest:present.at(-1),average:present.length?present.reduce((a,b)=>a+b,0)/present.length:undefined,peak:present.length?present.reduce((a,b)=>Math.max(a,b)):undefined}}).sort((a,b)=>(b.average??-Infinity)-(a.average??-Infinity));const fold=all.length>limit&&additiveUnits.has(unit);const shown=all.slice(0,fold?limit-1:limit);const rest=all.slice(shown.length);const other=fold?{name:`Other (${rest.length})`,values:timestamps.map((_,t)=>rest.some(s=>s.values[t]!=null)?rest.reduce((sum,s)=>sum+(s.values[t]??0),0):null)}:undefined;const slots=new Map([...shown].map(s=>s.name).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map((name,i)=>[name,i+1]));return {timestamps,all,shown,other,slots}}
