import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import * as Dialog from '@radix-ui/react-dialog';
import {X} from 'lucide-react';
import {api,setCsrf,type Session} from './api';
export function isAdministrator(session?:Session){return session?.canManageSessions??(session?.user.role==='administrator'||session?.user.roles?.includes('administrator')===true)}
type ManagedSession={handle:string;userId:string;provider:string;roles:string[];expires:string;current:boolean};
type SessionPage={data:ManagedSession[];meta:{limit:number;offset:number;hasMore:boolean}};
export function SessionAdministration({session,onSignedOut}:{session?:Session;onSignedOut:()=>void}){
  const client=useQueryClient();const [offset,setOffset]=useState(0);const [selected,setSelected]=useState<ManagedSession|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const allowed=isAdministrator(session);
  const query=useQuery({queryKey:['admin-sessions',offset],queryFn:async()=>await api<ManagedSession[]>(`/admin/sessions?limit=25&offset=${offset}`) as unknown as SessionPage,enabled:allowed&&!session?.demo});
  async function revoke(){if(!selected)return;setBusy(true);setError('');try{const result=await api<{ok:boolean;current:boolean}>(`/admin/sessions/${encodeURIComponent(selected.handle)}/revoke`,{method:'POST',body:JSON.stringify({confirm:true})});if(result.data.current){await client.cancelQueries();client.clear();setCsrf('');onSignedOut();return}setSelected(null);setNotice('Session revoked.');await client.invalidateQueries({queryKey:['admin-sessions']});}catch(e){setError(e instanceof Error?e.message:'Unable to revoke session. Try again.')}finally{setBusy(false)}}
  if(!allowed)return <div className="error-box" role="alert">Administrator access required to manage sessions.</div>;
  if(session?.demo)return <section className="panel"><div className="panel-title"><div><h2>Demo sessions</h2><p>Demo access is automatic. No personal session is active. Session revocation is unavailable in the simulator.</p></div><span className="tiny-badge">DEMO</span></div></section>;
  const rows=query.data?.data??[];
  return <section className="panel session-administration"><div className="panel-title"><div><h2>Active sessions</h2><p>Review authenticated sessions and revoke access. Up to 25 sessions per page.</p></div><button className="button" disabled={query.isFetching||busy} onClick={()=>query.refetch()}>Refresh sessions</button></div>{query.isLoading?<p role="status" className="loading">Loading sessions…</p>:query.error?<div className="inline-error" role="alert">Unable to load sessions: {query.error.message}<button className="button" onClick={()=>query.refetch()}>Retry</button></div>:rows.length?<div className="session-table-scroll"><table className="session-table"><thead><tr><th scope="col">User</th><th scope="col">Provider</th><th scope="col">Roles</th><th scope="col">Expires</th><th scope="col">Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.handle}><td><strong>{row.userId}</strong>{row.current&&<span className="tag">Current session</span>}</td><td>{row.provider}</td><td>{row.roles.join(', ')||'No roles'}</td><td><time dateTime={row.expires}>{new Date(row.expires).toLocaleString()}</time></td><td><button className="button danger-button" aria-label={`Revoke session for ${row.userId}`} disabled={busy} onClick={()=>{setSelected(row);setError('');setNotice('')}}>Revoke</button></td></tr>)}</tbody></table></div>:<div className="empty">No active sessions.</div>}<div className="panel-bottom session-pagination"><span>Page {Math.floor(offset/25)+1} · {rows.length} sessions</span><div><button className="button" disabled={!offset||query.isFetching||busy} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous page</button><button className="button" disabled={!query.data?.meta.hasMore||offset>=10000||query.isFetching||busy} onClick={()=>setOffset(offset+25)}>Next page</button></div></div>{notice&&<p role="status">{notice}</p>}<Dialog.Root open={!!selected} onOpenChange={open=>{if(!open&&!busy)setSelected(null)}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog"><Dialog.Title>Revoke session</Dialog.Title><Dialog.Description>Revoke this session for {selected?.userId}? The user must sign in again to regain access.{selected?.current?' You will be signed out and returned to login.':''}</Dialog.Description><Dialog.Close className="dialog-close" disabled={busy} aria-label="Close"><X size={18}/></Dialog.Close>{error&&<p className="inline-error" role="alert">Unable to revoke session: {error}. Try again.</p>}<div className="wizard-actions"><button className="button" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button><button className="button danger-button" disabled={busy} onClick={revoke}>{busy?'Revoking…':'Confirm revocation'}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root></section>;
}
